[general]
import = ["/home/asus/dotfiles/alacritty/.config/alacritty/nord.toml"]
live_config_reload = true

[window]
opacity = 0.70
blur = true
decorations = "None"
startup_mode = "Maximized"
padding = { x = 10, y = 10 }

[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[[mouse.bindings]]
mouse = "Right"
action = "Paste"

[terminal.shell]
program = "/usr/bin/fish"

[selection]
save_to_clipboard = true
