general {
#    grace = 2
    hide_cursor = true
#    no_fade_in = false
#    disable_loading_bar = true
}

background {
    monitor =
    path = ~/Pictures/wallpapers/River.png

    blur_passes = 4
    blur_size = 8

    noise = 0.02
    contrast = 1.15
    brightness = 0.75
    vibrancy = 0.20
    vibrancy_darkness = 0.2
}

############################
# TIME
############################

label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"

    font_family = JetBrainsMono Nerd Font
    font_size = 96

    color = rgba(ffffffff)

    position = 0, 180
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date +"%A, %d %B %Y"

    font_family = JetBrainsMono Nerd Font
    font_size = 24

    color = rgba(ccccccff)

    position = 0, 110
    halign = center
    valign = center
}

############################
# USER
############################

label {
    monitor =
    text =  $USER

    font_family = JetBrainsMono Nerd Font
    font_size = 22

    color = rgba(f5f5f5ff)

    position = 0, 40
    halign = center
    valign = center
}

############################
# HOSTNAME
############################

label {
    monitor =

    text = cmd[update:1000] hostname

    font_family = JetBrainsMono Nerd Font
    font_size = 18

    color = rgba(89ddffff)
    position = 0, -20

    halign = center
    valign = top
}


############################
# BATTERY
############################

label {
    monitor =
    text = cmd[update:5000] echo "󰁹 $(cat /sys/class/power_supply/BAT1/capacity)%"

    font_family = JetBrainsMono Nerd Font
    font_size = 18

    color = rgba(c3e88dff)

    position = -20, -20
    halign = right
    valign = top
}

############################
# PASSWORD BOX
############################

input-field {
    monitor =

    size = 340, 58

    outline_thickness = 2

    outer_color = rgba(89ddffff)
    inner_color = rgba(1a1a1acc)

    font_color = rgba(ffffffff)

    rounding = 12

    fade_on_empty = false

    placeholder_text = <i>Password...</i>

    dots_size = 0.24
    dots_spacing = 0.30
    dots_center = true

    check_color = rgba(c3e88dff)
    fail_color = rgba(ff5370ff)

    position = 0, -40

    halign = center
    valign = center
}

############################
# MEDIA
############################

label {
    monitor =
    text = cmd[update:1000] sh -c 'artist=$(playerctl metadata artist 2>/dev/null); title=$(playerctl metadata title 2>/dev/null); [ -n "$title" ] && printf "󰎆 %s - %s" "$artist" "$title" || printf " "'

    font_family = JetBrainsMono Nerd Font
    font_size = 18

    color = rgba(a5d6ffff)

    position = 0, 20
    halign = center
    valign = bottom
}

